server:
  port: 8081
  # dddd
  servlet:
    context-path: /demo






# Redis 配置
# spring.redis.database=1   Redis数据库索引
# spring.redis.host=127.0.0.1   Redis服务器地址
# spring.redis.port=6379   Redis服务器连接端口
# spring.redis.password=   Redis服务器连接密码（默认为空）
# spring.redis.jedis.pool.max-active=1000   连接池最大连接数（使用负值表示没有限制）
# spring.redis.jedis.pool.max.wait= -1    连接池最大阻塞等待时间（使用负值表示没有限制）
# spring.redis.jedis.pool.max-idle=10   连接池最大空闲连接
# spring.redis.jedis.pool.min-idle=2   连接池最小空闲连接
# spring.redis.timeout=0   连接超时时间（毫秒）

spring:
  redis:
    database: 2
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 100
        max-wait: -1
        max-idle: 10
        min-idle: 2
    timeout: 5000
# 配置thymeleaf模板
  thymeleaf:
  # 关闭缓存，即使刷新，上线生产环境需要改为true
    cache: false
    # 默认，可不写
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html

